CREATE TABLE customer
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at BIGINT,
    updated_at BIGINT,
    full_name  VARCHAR(50)         NOT NULL,
    email      VARCHAR(100) UNIQUE NOT NULL CHECK (LENGTH(email) >= 5),
    phone      VARCHAR(14),
    is_active  BOOLEAN DEFAULT TRUE
);
